server:
  port: 8090 # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: false
      charset: UTF-8

springfox:
  documentation:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
