spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

server:
  port: 8090 # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5272/eureka/

springfox:
  documentation:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  login:
    url: http://localhost:8762/
  medicalRecordManagement:
    url: http://localhost:8777/
  system:
    url: http://localhost:5678/
  exam:
    url: http://localhost:8778/
