spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 750MB

server:
  port: 8090 # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: false
      charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8085/eureka/

springfox:
  documentation:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

application:
  login:
    url: http://host.docker.internal:8086/
  medicalRecordManagement:
    url: http://host.docker.internal:8088/
  system:
    url: http://host.docker.internal:8087/
  exam:
    url: http://host.docker.internal:8089/
