spring:
  profiles:
    active: @profileActive@
  application:
    name: intermediator-service # 名称自己选新的，需要能说明模块大致内容，不要重复

server:
  port: ${server.port} # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: ${server.servlet.encoding.force-response}
      charset: ${server.servlet.encoding.charset}

springfox:
  documentation:
    enabled: ${springfox.documentation.enabled}

springdoc:
  api-docs:
    enabled: ${springdoc.api-docs.enabled}
  swagger-ui:
    enabled: ${springdoc.swagger-ui.enabled}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 30 # 拉取服务注册信息间隔（缺省为30s）
    service-url:
      defaultZone: http://localhost:5272/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
