server:
  port: 8090 # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

springfox:
  documentation:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
