server:
  port: 5678

spring:
  datasource:
    username: virtualPetHospital
    password: virtualPetHospital
    url: jdbc:mysql://localhost:3306/system?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5272/eureka/
