spring:
  profiles:
    active: @profileActive@
  application:
    name: medicalRecordManagement-service
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  sql:
    init:
      mode: ${spring.sql.init.mode}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      schema-locations:
        - classpath:database/medicalRecordManagement_initialize.sql
      data-locations:
        - classpath:database/medicalRecordManagement_data.sql

server:
  port: ${server.port}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30      
    lease-expiration-duration-in-seconds: 90 
  client:
    registry-fetch-interval-seconds: 30 
    service-url:
      defaultZone: http://localhost:5272/eureka/
    healthcheck:
      enabled: true 

