server:
  port: 8089

spring:
  datasource:
    username: virtualPetHospital
    password: virtualPetHospital
    url: jdbc:mysql://localhost:3306/exam?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
