server:
  port: 8086

spring:
  datasource:
    username: virtualPetHospital
    password: virtualPetHospital
    url: jdbc:mysql://localhost:3306/login?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: never
