server:
  port: 5273 # 端口号自己配新的，不要重复
spring:
  application:
    name: swagger # 名称自己选新的，需要能说明模块大致内容，不要重复

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 30 # 拉取服务注册信息间隔（缺省为30s）
    service-url:
      defaultZone: http://localhost:5272/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）

springfox:
  documentation:
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  group-configs:
    - group: project
      packagesToScan: pet.hospital.backend
    - group: swagger
      packagesToScan: pet.hospital.backend.swagger
    - group: login
      packagesToScan: pet.hospital.backend.login
    - group: medicalRecordManagement
      packagesToScan: pet.hospital.backend.medicalRecordManagement
    - group: system
      packagesToScan: pet.hospital.backend.system
